### ISSUE TITLE
Add character limit assertion for the repo name in pipelineUtils.groovy

### ISSUE THREAD

**Issue by billmania42** [elcicd/el-CICD#1]
I would like to add an assertion check that verifies that the repo name is <=42 characters.  This is needed due to the 63 character limit in OpenShift/Kubernetes.  As el-CICD uses the repo name as a portion of the name of derived OpenShift artifacts, if the repo name is >42 characters, then the derived objects will have names over the 63 character OpenShift/Kubernetes limit.  It looks like we could add the assertion to the pipelineUtils.groovy file, near line 154.  Looks like we could replace line 155 with:
 [\w\-]{1,42}

**Comment by elcicd** [comment]
After reviewing this, we'll probably add some validation in the future based on all repo names contained in the project, and fail a build if any generated K8S/OKD resource names exceeded 63 characters.  We'll also make the limit fungible in the config files, so that if this limit changes in the future (hopefully), it can easily be adjusted by end users.

**Comment by hippyod** [comment]
@billmania42 OK, say I trim all labels over 63 characters to 48 characters, and then append with a `derivePassword` pseudo random random value (14 characters long).   Just in case you need your labels to remain unique and some are similar.  I am using this for the `el-cicd.io/selector` selector label the el-Cicd-deploy charts use.  Look in `el-CICD-deploy/charts/elCicdCommon/templates/_helpers.tpl` for the code (starting at line 60) for an example.

This functionality will be toggled on only when wanted (such as el-CICD default deploys).  If you write your own charts outside el-CICD you'll have to turn it on on your own.  It will eat those values without a good way to warn you.

**Comment by hippyod** [comment]
Deployments using the el-CICD Chart will should now automatically truncate names properly.  Deployments using other charts or Kustomize setups should validate their own data.
